[project]
name = "get-block-info"
authors = []
description = "Expose the get-block-info clarity values"
telemetry = false
requirements = []

[repl]
costs_version = 2
parser_version = 2
[repl.analysis]
passes = ["check_checker"]
[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[contracts.get-block-info]
path = "contracts/get-block-info.clar"
depends_on = []
